"""FAC-driven experimental DRM Opus receiver.

The physical DRM mode and spectrum occupancy are bootstrap parameters. MSC and
SDC constellation mappings are read from the decoded FAC instead of being
trusted from the supplied ``transm_params`` object.
"""

import numpy
import pmt
from gnuradio import blocks, gr

import drm_next as drm


def _fac_crc_valid(bits):
    """Check the DRM FAC CRC-8 generated by ``enqueue_crc``."""
    if len(bits) < 72:
        return False
    state = [1] * 8
    for value in bits[:64]:
        previous = state[:]
        feedback = (int(value) & 1) ^ previous[0]
        state[7] = feedback
        state[6] = previous[7]
        state[5] = previous[6] ^ feedback
        state[4] = previous[5] ^ feedback
        state[3] = previous[4] ^ feedback
        state[0:3] = previous[1:4]
    expected = [value ^ 1 for value in state]
    return list(int(value) & 1 for value in bits[64:72]) == expected


class _fac_mapping_detector(gr.sync_block):
    """Parse valid FAC vectors and publish mapping changes."""

    _MSC_MODES = {(1, 1): 1, (0, 0): 2, (1, 0): 3, (0, 1): 4}

    def __init__(self, fac_length, initial_msc_mapping):
        gr.sync_block.__init__(
            self,
            name="DRM FAC Mapping Detector",
            in_sig=[(numpy.uint8, fac_length)],
            out_sig=None,
        )
        self.message_port_register_out(pmt.intern("mapping"))
        self._last = (int(initial_msc_mapping), None, None)

    def work(self, input_items, output_items):
        for bits in input_items[0]:
            if not _fac_crc_valid(bits):
                continue
            msc_mapping = self._MSC_MODES.get((int(bits[8]), int(bits[9])))
            sdc_mapping = 1 if int(bits[10]) else 0
            long_interleaving = not bool(int(bits[7]))
            if msc_mapping not in (1, 2):
                continue  # Hierarchical mappings are not implemented yet.
            detected = (msc_mapping, sdc_mapping, long_interleaving)
            if detected != self._last:
                print("DRM FAC: detected MSC {}-QAM, SDC {}-QAM".format(
                    16 if msc_mapping == 1 else 64,
                    4 if sdc_mapping == 1 else 16))
                self._last = detected
            message = pmt.make_dict()
            message = pmt.dict_add(message, pmt.intern("msc_mapping"),
                                   pmt.from_long(msc_mapping))
            message = pmt.dict_add(message, pmt.intern("sdc_mapping"),
                                   pmt.from_long(sdc_mapping))
            message = pmt.dict_add(message, pmt.intern("long_interleaving"),
                                   pmt.from_bool(long_interleaving))
            self.message_port_pub(pmt.intern("mapping"), message)
        return len(input_items[0])


class _audio_mapping_selector(gr.sync_block):
    """Select a mapping/interleaver audio branch from FAC messages."""

    def __init__(self, initial_msc_mapping, initial_long_interleaving):
        gr.sync_block.__init__(
            self,
            name="DRM MSC Mapping Selector",
            in_sig=[numpy.float32, numpy.float32, numpy.float32, numpy.float32],
            out_sig=[numpy.float32],
        )
        self._selected = self._index(initial_msc_mapping, initial_long_interleaving)
        self._long_interleaving = bool(initial_long_interleaving)
        self._sdc_mapping = None
        self.message_port_register_in(pmt.intern("mapping"))
        self.set_msg_handler(pmt.intern("mapping"), self._handle_mapping)

    def _handle_mapping(self, message):
        msc = pmt.dict_ref(message, pmt.intern("msc_mapping"), pmt.PMT_NIL)
        sdc = pmt.dict_ref(message, pmt.intern("sdc_mapping"), pmt.PMT_NIL)
        long_interleaving = pmt.dict_ref(
            message, pmt.intern("long_interleaving"), pmt.PMT_NIL)
        mapping = None
        if pmt.is_integer(msc):
            value = pmt.to_long(msc)
            if value in (1, 2):
                mapping = value
        if pmt.is_bool(long_interleaving):
            self._long_interleaving = pmt.to_bool(long_interleaving)
        if mapping is not None:
            self._selected = self._index(mapping, self._long_interleaving)
        if pmt.is_integer(sdc):
            self._sdc_mapping = pmt.to_long(sdc)

    def work(self, input_items, output_items):
        count = min(*(len(items) for items in input_items), len(output_items[0]))
        output_items[0][:count] = input_items[self._selected][:count]
        return count

    @staticmethod
    def _index(mapping, long_interleaving):
        return (int(mapping) - 1) * 2 + (1 if long_interleaving else 0)


class drm_opus_auto_receiver_ccf(gr.hier_block2):
    """Receive experimental Opus audio with FAC-driven MSC/SDC mapping.

    The receiver owns its parameters; it does not share state with a
    transmitter. Robustness mode, spectrum occupancy, MSC protection level,
    and audio sample rate bootstrap the current implementation. Both supported
    MSC mappings/interleaver depths and both SDC mappings are decoded in
    parallel. Valid FAC frames choose the audio branch at runtime.
    """

    def __init__(self, rm=1, so=3, msc_protection=1, audio_sample_rate=24000):
        gr.hier_block2.__init__(
            self,
            "DRM Automatic Opus Receiver",
            gr.io_signature(1, 1, gr.sizeof_gr_complex),
            gr.io_signature(1, 1, gr.sizeof_float),
        )
        if msc_protection < 0 or msc_protection > 3:
            raise ValueError("MSC protection level must be between 0 and 3")
        self.tp = drm.transm_params(
            rm, so, False, 0, 1, 0, min(msc_protection, 1), 1, 0,
            False, audio_sample_rate, "receiver", "")
        tp = self.tp
        cfg = tp.cfg()

        # Mapping does not change the OFDM geometry or cell positions, so one
        # synchronized/equalized front end can feed every candidate decoder.
        self.synchronizer = drm.ofdm_synchronizer_cc(tp.ofdm().nfft(), tp.ofdm().n_cp())
        self.demodulator = drm.ofdm_demodulator_cc(
            tp.ofdm().nfft(), tp.ofdm().n_cp(), True)
        self.equalizer = drm.pilot_equalizer_vcc(tp)
        self.cell_demapper = drm.cell_demapping_cc(tp)
        self.connect(self, self.synchronizer, self.demodulator,
                     self.equalizer, self.cell_demapper)

        # Candidate parameter objects must remain alive for their C++ blocks.
        self._candidate_params = {}
        for mapping in (1, 2):
            protection = min(msc_protection, 1) if mapping == 1 else msc_protection
            for long_interleaving in (False, True):
                self._candidate_params[("MSC", mapping, long_interleaving)] = \
                    drm.transm_params(
                        rm, so, False, 0, mapping, 0, protection, 1, 0,
                        long_interleaving, audio_sample_rate, "receiver", "")
        for mapping in (0, 1):
            self._candidate_params[("SDC", mapping)] = drm.transm_params(
                rm, so, False, 0, 1, 0, min(msc_protection, 1), mapping, 0,
                False, audio_sample_rate, "receiver", "")

        fac_vectors = self._build_fac_path()
        self.fac_detector = _fac_mapping_detector(tp.fac().L(), cfg.msc_mapping())
        self.connect(fac_vectors, self.fac_detector)

        # Decode both SDC constellations so an FAC mapping change never stalls
        # or invalidates the receiver graph. SDC entity parsing is the next
        # stage needed for automatic protection-level/service selection.
        self.sdc_sinks = []
        for mapping in (0, 1):
            candidate = self._candidate_params[("SDC", mapping)]
            vector = self._build_control_path((self.cell_demapper, 1), candidate, "SDC")
            sink = blocks.null_sink(gr.sizeof_char * candidate.sdc().L())
            self.connect(vector, sink)
            self.sdc_sinks.append(sink)

        audio_outputs = []
        for mapping in (1, 2):
            for long_interleaving in (False, True):
                candidate = self._candidate_params[("MSC", mapping, long_interleaving)]
                audio_outputs.append(self._build_msc_path(candidate))

        self.selector = _audio_mapping_selector(1, False)
        self.msg_connect(self.fac_detector, "mapping", self.selector, "mapping")
        for index, audio in enumerate(audio_outputs):
            self.connect(audio, (self.selector, index))
        self.connect(self.selector, self)

    @staticmethod
    def _qam_table(tp, channel):
        params = tp.msc() if channel == "MSC" else tp.sdc() if channel == "SDC" else tp.fac()
        order = params.mod_order()
        tables = tp.cfg().ptables()
        return tables.d_QAM4 if order == 2 else tables.d_QAM16 if order == 4 \
            else tables.d_QAM64SM

    @staticmethod
    def _bit_sequences(tp, channel):
        params = tp.msc() if channel == "MSC" else tp.sdc() if channel == "SDC" else tp.fac()
        levels = 1 if channel == "FAC" else params.n_levels_mlc()
        if channel == "MSC" and tp.cfg().msc_mapping() == 2:
            return [None, params.bit_interl_seq_1_2(), params.bit_interl_seq_2_2()]
        result = [params.bit_interl_seq_0_2()]
        if levels > 1:
            result.append(params.bit_interl_seq_1_2())
        return result

    def _decode_cells(self, source, tp, channel, cells):
        params = tp.fac() if channel == "FAC" else tp.sdc()
        levels = 1 if channel == "FAC" else params.n_levels_mlc()
        flatten = blocks.vector_to_stream(gr.sizeof_gr_complex, cells)
        demapper = drm.qam_demapper_cb(
            self._qam_table(tp, channel), params.mod_order(), levels)
        decoder = drm.mlc_decoder_bb(tp, channel)
        self.connect(source, flatten, demapper)
        deinterleavers = []
        for level, sequence in enumerate(self._bit_sequences(tp, channel)):
            if sequence is None:
                self.connect((demapper, level), (decoder, level))
            else:
                block = drm.deinterleaver_bb(sequence)
                deinterleavers.append(block)
                self.connect((demapper, level), block, (decoder, level))
        descrambler = drm.scrambler_bb(params.L())
        vector = blocks.stream_to_vector(gr.sizeof_char, params.L())
        self.connect(decoder, descrambler, vector)
        return vector, (flatten, demapper, decoder, deinterleavers, descrambler)

    def _build_fac_path(self):
        cells = self.tp.fac().N() * self.tp.ofdm().M_TF()
        vector, self.fac_blocks = self._decode_cells(
            (self.cell_demapper, 2), self.tp, "FAC", cells)
        return vector

    def _build_control_path(self, source, tp, channel):
        vector, chain = self._decode_cells(source, tp, channel, tp.sdc().N())
        if not hasattr(self, "sdc_blocks"):
            self.sdc_blocks = []
        self.sdc_blocks.append(chain)
        return vector

    def _build_msc_path(self, tp):
        total_cells = tp.msc().N_MUX() * tp.ofdm().M_TF()
        flatten = blocks.vector_to_stream(gr.sizeof_gr_complex, total_cells)
        cell_deinterleaver = drm.deinterleaver_cc(
            tp.msc().cell_interl_seq(), tp.cfg().long_interl(), drm.INTL_DEPTH_DRM)
        levels = tp.msc().n_levels_mlc()
        demapper = drm.qam_demapper_cb(
            self._qam_table(tp, "MSC"), tp.msc().mod_order(), levels)
        decoder = drm.mlc_decoder_bb(tp, "MSC")
        self.connect((self.cell_demapper, 0), flatten, cell_deinterleaver, demapper)
        bit_deinterleavers = []
        for level, sequence in enumerate(self._bit_sequences(tp, "MSC")):
            if sequence is None:
                self.connect((demapper, level), (decoder, level))
            else:
                block = drm.deinterleaver_bb(sequence)
                bit_deinterleavers.append(block)
                self.connect((demapper, level), block, (decoder, level))
        descrambler = drm.scrambler_bb(tp.msc().L_MUX())
        frame = blocks.stream_to_vector(gr.sizeof_char, tp.msc().L_MUX())
        audio = drm.opus_audio_decoder_bf(tp)
        self.connect(decoder, descrambler, frame, audio)
        if not hasattr(self, "msc_blocks"):
            self.msc_blocks = []
        self.msc_blocks.append((flatten, cell_deinterleaver, demapper, decoder,
                                bit_deinterleavers, descrambler, frame, audio))
        return audio
